version: '3.4'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=dummykey
      - AWS_SECRET_ACCESS_KEY=dummysecret